name: sistema_horarios
description: Sistema Generador de Horarios Escolares
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  pdf: ^3.11.1
  printing: ^5.13.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.4   # ← nuevo: guardar PDF en carpeta Descargas
  file_picker: ^8.0.0     # ← nuevo: permitir al usuario elegir dónde guardar el PDF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true